# Generated by Django 4.0.2 on 2022-04-07 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_followings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followings',
        ),
    ]
